version: '3'

services:
  bot:
    build:
      context: .
    restart: on-failure
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=value
      - REDIS_HOST=value
      - REDIS_PORT=value
      